product-name: cf
product-properties:
  .cloud_controller.allow_app_ssh_access:
    value: true
  .cloud_controller.apps_domain:
    value: {{ (ds "data").apps_domain }}
  .cloud_controller.default_app_memory:
    value: 1024
  .cloud_controller.default_app_ssh_access:
    value: true
  .cloud_controller.default_disk_quota_app:
    value: 1024
  .cloud_controller.default_quota_max_number_services:
    value: 100
  .cloud_controller.default_quota_memory_limit_mb:
    value: 10240
  .cloud_controller.enable_custom_buildpacks:
    value: true
  .cloud_controller.encrypt_key:
    value:
      secret: ((cloud_controller_encrypt_key))
  .cloud_controller.max_disk_quota_app:
    value: 2048
  .cloud_controller.max_file_size:
    value: 1024
  .cloud_controller.security_event_logging_enabled:
    value: true
  .cloud_controller.staging_timeout_in_seconds:
    value: 900
  .cloud_controller.system_domain:
    value: {{ (ds "data").sys_domain }}
  .diego_brain.starting_container_count_maximum:
    value: 200
  .ha_proxy.skip_cert_verify:
    value: false
  .mysql.cli_history:
    value: true
  .mysql.max_connections:
    value: 3500
  .mysql.prevent_node_auto_rejoin:
    value: false
  .mysql.remote_admin_access:
    value: false
  .mysql_monitor.poll_frequency:
    value: 30
  .mysql_monitor.recipient_email:
    value: ((mysql_email))
  .mysql_monitor.write_read_delay:
    value: 20
  .mysql_proxy.shutdown_delay:
    value: 30
  .mysql_proxy.startup_delay:
    value: 0
  .nfs_server.blobstore_internal_access_rules:
    value: allow 10.0.0.0/8;,allow 172.16.0.0/12;,allow 192.168.0.0/16;
  .properties.autoscale_api_disable_connection_pooling:
    value: false
  .properties.autoscale_api_instance_count:
    value: 1
  .properties.autoscale_enable_verbose_logging:
    value: false
  .properties.autoscale_instance_count:
    value: 3
  .properties.autoscale_metric_bucket_count:
    value: 120
  .properties.autoscale_scaling_interval_in_seconds:
    value: 35
  .properties.cc_api_rate_limit:
    selected_option: disable
    value: disable
  .properties.cc_logging_level:
    value: info
  .properties.ccdb_connection_validation_timeout:
    value: 3600
  .properties.ccdb_read_timeout:
    value: 3600
  .properties.cf_networking_database_connection_timeout:
    value: 120
  .properties.cf_networking_enable_space_developer_self_service:
    value: true
  .properties.cf_networking_internal_domain:
    value: apps.internal
  .properties.cloud_controller_default_health_check_timeout:
    value: 60
  .properties.cloud_controller_temporary_disable_deployments:
    value: false
  .properties.container_networking:
    selected_option: enable
    value: enable
  .properties.container_networking_interface_plugin:
    selected_option: silk
    value: silk
  .properties.container_networking_interface_plugin.silk.enable_log_traffic:
    value: false
  .properties.container_networking_interface_plugin.silk.enable_policy_enforcement:
    value: true
  .properties.container_networking_interface_plugin.silk.iptables_accepted_udp_logs_per_sec:
    value: 100
  .properties.container_networking_interface_plugin.silk.iptables_denied_logs_per_sec:
    value: 1
  .properties.container_networking_interface_plugin.silk.network_mtu:
    value: 1454
  .properties.container_networking_interface_plugin.silk.vtep_port:
    value: 4789
  .properties.credhub_database:
    selected_option: internal_mysql
    value: internal_mysql
  .properties.credhub_hsm_provider_client_certificate:
    value:
      cert_pem: ""
      private_key_pem: ""
  .properties.credhub_hsm_provider_partition_password:
    value:
      secret: ""
  .properties.credhub_key_encryption_passwords:
    value:
    - key:
        secret: ((credhub_key_encryption_password))
      name: default
      primary: true
      provider: internal
  .properties.diego_database_max_open_connections:
    value: 100
  .properties.diego_log_timestamp_format:
    selected_option: rfc3339
    value: rfc3339
  .properties.enable_smb_volume_driver:
    value: false
  .properties.enable_tls_to_internal_pxc:
    value: true
  .properties.experimental_dynamic_egress_enforcement:
    value: true
  .properties.garden_disk_cleanup:
    selected_option: reserved
    value: reserved
  .properties.gorouter_ssl_ciphers:
    value: ECDHE-RSA-AES128-GCM-SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  .properties.haproxy_client_cert_validation:
    selected_option: none
    value: none
  .properties.haproxy_forward_tls:
    selected_option: disable
    value: disable
  .properties.haproxy_hsts_support:
    selected_option: disable
    value: disable
  .properties.haproxy_max_buffer_size:
    value: 16384
  .properties.haproxy_ssl_ciphers:
    value: DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
  .properties.istio:
    selected_option: disable
    value: disable
  .properties.locket_database_max_open_connections:
    value: 200
  .properties.metric_registrar_blacklisted_tags:
    value: deployment,job,index,id
  .properties.metric_registrar_enabled:
    value: true
  .properties.metric_registrar_scrape_interval_in_seconds:
    value: 35
  .properties.mysql_activity_logging:
    selected_option: enable
    value: enable
  .properties.mysql_activity_logging.enable.audit_logging_events:
    value: connect,query
  .properties.networking_poe_ssl_certs:
    value:
    - certificate:
        cert_pem: |
{{ (ds "data").ssl_cert | strings.Indent 10 }}
        private_key_pem: |
{{ (ds "data").ssl_private_key | strings.Indent 10 }}
      name: router-cert
  .properties.networkpolicyserver_database_max_open_connections:
    value: 200
  .properties.networkpolicyserverinternal_database_max_open_connections:
    value: 200
  .properties.nfs_volume_driver:
    selected_option: enable
    value: enable
  .properties.nfs_volume_driver.enable.ldap_service_account_password:
    value:
      secret: ""
  .properties.push_apps_manager_app_poll_interval:
    value: 10
  .properties.push_apps_manager_currency_lookup:
    value: '{ "usd": "$", "eur": "â‚¬" }'
  .properties.push_apps_manager_display_plan_prices:
    value: false
  .properties.push_apps_manager_enable_invitations:
    value: true
  .properties.push_apps_manager_poll_interval:
    value: 30
  .properties.route_integrity:
    selected_option: mutual_tls_verify
    value: mutual_tls_verify
  .properties.route_services:
    selected_option: enable
    value: enable
  .properties.route_services.enable.ignore_ssl_cert_verification:
    value: false
  .properties.router_backend_max_conn:
    value: 500
  .properties.router_client_cert_validation:
    selected_option: request
    value: request
  .properties.router_enable_proxy:
    value: false
  .properties.router_keepalive_connections:
    selected_option: enable
    value: enable
  .properties.routing_disable_http:
    value: false
  .properties.routing_log_client_ips:
    selected_option: log_client_ips
    value: log_client_ips
  .properties.routing_minimum_tls_version:
    selected_option: tls_v1_2
    value: tls_v1_2
  .properties.routing_tls_termination:
    selected_option: load_balancer
    value: load_balancer
  .properties.saml_signature_algorithm:
    value: SHA256
  .properties.secure_service_instance_credentials:
    value: true
  .properties.security_acknowledgement:
    value: X
  .properties.silk_database_max_open_connections:
    value: 200
  .properties.smoke_tests:
    selected_option: on_demand
    value: on_demand
  .properties.smtp_auth_mechanism:
    value: plain
  .properties.smtp_credentials:
    value:
      identity: ""
      password: ""
  .properties.smtp_enable_starttls_auto:
    value: false
  .properties.stack_migration_acknowledgement:
    value: X
  .properties.syslog_drop_debug:
    value: true
  .properties.syslog_metrics_to_syslog_enabled:
    value: true
  .properties.syslog_tls:
    selected_option: disabled
    value: disabled
  .properties.syslog_use_tcp_for_file_forwarding_local_transport:
    value: false
  .properties.system_blobstore:
    selected_option: internal
    value: internal
  .properties.system_blobstore_ccdroplet_max_staged_droplets_stored:
    value: 2
  .properties.system_blobstore_ccpackage_max_valid_packages_stored:
    value: 2
  .properties.system_database:
    selected_option: internal_pxc
    value: internal_pxc
  .properties.tcp_routing:
    selected_option: disable
    value: disable
  .properties.uaa:
    selected_option: internal
    value: internal
  .properties.uaa.internal.password_expires_after_months:
    value: 0
  .properties.uaa.internal.password_max_retry:
    value: 5
  .properties.uaa.internal.password_min_length:
    value: 0
  .properties.uaa.internal.password_min_lowercase:
    value: 0
  .properties.uaa.internal.password_min_numeric:
    value: 0
  .properties.uaa.internal.password_min_special:
    value: 0
  .properties.uaa.internal.password_min_uppercase:
    value: 0
  .properties.uaa_database:
    selected_option: internal_mysql
    value: internal_mysql
  .properties.uaa_session_cookie_max_age:
    value: 28800
  .properties.uaa_session_idle_timeout:
    value: 1800
  .router.disable_insecure_cookies:
    value: false
  .router.drain_wait:
    value: 20
  .router.enable_isolated_routing:
    value: false
  .router.enable_write_access_logs:
    value: true
  .router.enable_zipkin:
    value: true
  .router.frontend_idle_timeout:
    value: 900
  .router.lb_healthy_threshold:
    value: 20
  .router.request_timeout_in_seconds:
    value: 900
  .uaa.apps_manager_access_token_lifetime:
    value: 3600
  .uaa.cf_cli_access_token_lifetime:
    value: 7200
  .uaa.cf_cli_refresh_token_lifetime:
    value: 1209600
  .uaa.customize_password_label:
    value: Password
  .uaa.customize_username_label:
    value: Email
  .uaa.proxy_ips_regex:
    value: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}
  .uaa.service_provider_key_credentials:
    value:
      cert_pem: |
{{ (ds "data").ssl_cert | strings.Indent 8 }}
      private_key_pem: |
{{ (ds "data").ssl_private_key | strings.Indent 8 }}
  .uaa.service_provider_key_password:
    value:
      secret: ""
network-properties:
  network:
    name: {{ (ds "data").pas_subnet_name }}
  other_availability_zones:
  - name: {{ index (ds "data").azs 0 }}
  - name: {{ index (ds "data").azs 1 }}
  - name: {{ index (ds "data").azs 2 }}
  singleton_availability_zone:
    name: {{ index (ds "data").azs 0 }}
resource-config:
  backup_restore:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: true
  clock_global:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  cloud_controller:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  cloud_controller_worker:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  credhub:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  diego_brain:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
    elb_names:
    - tcp:{{ (ds "data").ssh_lb_name }}
  diego_cell:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  diego_database:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  doppler:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  ha_proxy:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  istio_control:
    instances: 0
    instance_type:
      id: automatic
    internet_connected: true
  istio_router:
    instances: 0
    instance_type:
      id: automatic
    internet_connected: true
  loggregator_trafficcontroller:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  mysql:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: true
  mysql_monitor:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  mysql_proxy:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  nats:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  nfs_server:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: true
  route_syncer:
    instances: 0
    instance_type:
      id: automatic
    internet_connected: true
  router:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
    elb_names:
    - tcp:{{ (ds "data").ws_router_pool }}
    - http:{{ (ds "data").http_lb_backend_name }}
  syslog_adapter:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  syslog_scheduler:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  tcp_router:
    instances: 0
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: true
  uaa:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
errand-config:
  deploy-autoscaler:
    post-deploy-state: true
  deploy-notifications:
    post-deploy-state: true
  deploy-notifications-ui:
    post-deploy-state: true
  metric_registrar_smoke_test:
    post-deploy-state: false
  nfsbrokerpush:
    post-deploy-state: true
  push-apps-manager:
    post-deploy-state: true
  push-usage-service:
    post-deploy-state: true
  smbbrokerpush:
    post-deploy-state: false
  smoke_tests:
    post-deploy-state: true
  test-autoscaling:
    post-deploy-state: true
